# Generated by Django 5.1.3 on 2024-11-24 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tertulia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tertulia_name', models.CharField(max_length=100)),
                ('tertulia_banner', models.ImageField(blank=True, default='fallback.png', upload_to='')),
                ('tertulia_description', models.TextField(blank=True, max_length=250)),
                ('tertulia_address', models.CharField(blank=True, max_length=250, null=True)),
                ('tertulia_horario', models.CharField(max_length=100)),
                ('tertulia_fecha_de_inicio', models.DateTimeField(null=True)),
                ('tertulia_sesiones', models.PositiveSmallIntegerField()),
                ('tertulia_encargado_picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('tertulia_encargado', models.CharField(max_length=100)),
                ('tertulia_lugares_disponibles', models.PositiveIntegerField(default=12)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
    ]
