# Generated by Django 5.1.4 on 2025-05-23 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tertulia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tertulia_name', models.CharField(max_length=100)),
                ('tertulia_banner', models.ImageField(upload_to='imagenes_admin/tertulias/')),
                ('tertulia_description', models.TextField(blank=True, max_length=450)),
                ('tertulia_address', models.CharField(blank=True, max_length=250, null=True)),
                ('tertulia_horario', models.CharField(max_length=100)),
                ('tertulia_fecha_de_inicio', models.DateField(null=True)),
                ('tertulia_sesiones', models.PositiveSmallIntegerField()),
                ('tertulia_encargado_picture', models.ImageField(upload_to='imagenes_admin/tertulias/foto-encargado')),
                ('tertulia_encargado', models.CharField(max_length=100)),
                ('tertulia_lugares', models.PositiveIntegerField(blank=True, null=True)),
                ('slug', models.IntegerField(default=0)),
            ],
        ),
    ]
