# Generated by Django 5.1.3 on 2024-11-25 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tertulias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tertulia',
            name='tertulia_encargado_picture',
            field=models.ImageField(blank=True, default='alonso.jpg', upload_to=''),
        ),
    ]
