# Generated by Django 5.1.3 on 2024-11-30 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tertulias', '0002_alter_tertulia_tertulia_encargado_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tertulia',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
