# Generated by Django 5.1.3 on 2024-12-13 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tertulias', '0003_alter_tertulia_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tertulia',
            name='tertulia_lugares_disponibles',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
