# Generated by Django 5.1.3 on 2024-12-14 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tertulias', '0004_alter_tertulia_tertulia_lugares_disponibles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tertulia',
            name='tertulia_lugares_disponibles',
        ),
        migrations.AddField(
            model_name='tertulia',
            name='tertulia_lugares',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
