# Generated by Django 5.1.4 on 2024-12-17 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tertulias', '0007_alter_tertulia_tertulia_lugares'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tertulia',
            name='tertulia_fecha_de_inicio',
            field=models.DateField(null=True),
        ),
    ]
