# Generated by Django 5.1.4 on 2024-12-17 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tertulias', '0008_alter_tertulia_tertulia_fecha_de_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tertulia',
            name='tertulia_description',
            field=models.TextField(blank=True, max_length=450),
        ),
    ]
