# Generated by Django 5.1.4 on 2025-05-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tertulias', '0009_alter_tertulia_tertulia_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tertulia',
            name='slug',
            field=models.IntegerField(default=0),
        ),
    ]
