# Generated by Django 5.1.3 on 2024-11-28 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_is_superadmin_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
    ]
