# Generated by Django 5.1.3 on 2024-11-28 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
    ]
