# Generated by Django 5.1.3 on 2024-11-29 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
