# Generated by Django 5.1.3 on 2024-12-13 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_contacto_delete_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='avisos',
        ),
    ]
