# Generated by Django 5.1.4 on 2025-05-23 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('banner', models.ImageField(upload_to='imagenes_admin/cursos/')),
                ('description', models.TextField()),
                ('duracion_curso', models.DurationField(null=True)),
                ('lugar_curso', models.TextField()),
                ('fecha_de_inicio', models.DateTimeField(null=True)),
                ('costo_del_curso', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('curso_encargado_picture', models.ImageField(upload_to='imagenes_admin/cursos/foto-encargado')),
                ('curso_encargado', models.CharField(max_length=100)),
                ('curso_lugares', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
