# Generated by Django 5.1.3 on 2024-12-15 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_curso_curso_encargado_curso_curso_encargado_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='curso_encargado_picture',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
    ]
