# Generated by Django 5.1.3 on 2024-12-15 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0002_student'),
        ('tertulias', '0007_alter_tertulia_tertulia_lugares'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='tertulia_name',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.DO_NOTHING, to='tertulias.tertulia'),
        ),
        migrations.AlterField(
            model_name='tertuliaform',
            name='tertulia_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tertulias.tertulia'),
        ),
    ]
